### PR TITLE
[DDO-2442] Make Sherlock state-loading more efficient

### PR DESCRIPTION
**Pull request by jack-r-warren**
- Moved the Sherlock StateReadWriter and StateLoader interfaces into `clients/sherlock`, where the implementations are, from `state/providers/sherlock`, where the usage is
- Changed some method names inside `state/providers/sherlock` to be a bit more clear about the behavior (there's multiple packages with `newEnvironments()` etc methods that do different things)

The meat of the change:
- Rather than requesting clusters, then environments, then chart releases for each destination, Sherlock state-loading now requests clusters, then environments, then chart releases, before sorting the chart releases into the correct destination in the state structure. This means the number of requests for each load goes from 2+len(clusters)+len(environments) to 3.
- In the above process, both before and after the change, there's a risk of race conditions if Sherlock's state changes in between when it responds to requests (imagine a BEE being created in between fetching environments and chart releases--chart releases would exist in the second response without an environment in the first). The state-loading process now detects this and retries automatically. It does not retry actual errors, just this race condition that isn't anyone's fault.

A fun fact:
- Thelma seems to load state twice for a lot of common operations--I'm not talking about the reload when creating a BEE; just running `thelma bee list` loads state twice
- I suspect this is mostly just because of [`ThelmaApp.State()`](https://github.com/broadinstitute/thelma/blob/main/internal/thelma/app/app.go#L110) which is called 17 places throughout Thelma's code base, a lot of them outside of tests. The "created-a-BEE-now-reload-state" is not one of them, the underlying `stateLoader.Load()` is actually called directly there. 
- There might be some opportunity to cache the response to that oft-called `ThelmaApp.State()`, but that could quickly impact algorithmic correctness of things I wouldn't think to test. I figure best not to over-optimize right now and we can kick that can down the road. I continue to think most of the wait time will be latency rather than actual compute time inside Sherlock (returning all chart releases across Terra without a proxy in the way takes 60ms, clusters 1ms, environments 6ms). Then again, loading twice is like running twice as many invocations of Thelma. We'll see.

### CODE REVIEW

**Comment by mflinn-broad** [comment]
> Moved the Sherlock StateReadWriter and StateLoader interfaces into clients/sherlock, where the implementations are, from state/providers/sherlock, where the usage is
Not a big deal but maybe `internal/state/api` is the right place for these? If we ever need to do another implementation of something that can read/write thelma state it would be kind of weird to import `clients/sherlock` in order to get access to these interfaces.

**Review by mflinn-broad — APPROVED** [review]
lgtm, one non-blocking organizational comment

**Comment by jack-r-warren** [comment]
> > Moved the Sherlock StateReadWriter and StateLoader interfaces into clients/sherlock, where the implementations are, from state/providers/sherlock, where the usage is
> 
> Not a big deal but maybe `internal/state/api` is the right place for these? If we ever need to do another implementation of something that can read/write thelma state it would be kind of weird to import `clients/sherlock` in order to get access to these interfaces.

These aren’t the overall interfaces, these are the Sherlock-specific ones that can work with Sherlock-specific types—what the Sherlock client directly implements. state/providers/sherlock uses it to implement the actual overall interfaces that work strictly with the abstracted Thelma types.

**Comment by mflinn-broad** [comment]
Sounds good, there's alot of interfaces involved here. Probably got them mixed up

**Pull request merged**
