### PR TITLE
Add service accounts cloud-extension/azure as part of bee setup

### PR DESCRIPTION
**Pull request by rtitle**
I've been doing this manually every time I set up a BEE but it's time to automate it. We need both google and azure `cloud-extension` policies in Sam to support creating pets on both clouds.

Q: how do I test this? (My Go is rusty). Ideally there would be a way to create a new BEE based off this thelma branch.

### CODE REVIEW

**Comment by aherbst-broad** [comment]
@rtitle any chance this gets merged soon? It continues to be a pain point on new bees. I'm happy to lend a hand testing.

**Comment by rtitle** [comment]
Some help testing would be great! I basically wrote this Go code but haven' tested at all.

Testing process:
1. Grab the thelma tarball from CI/CD (I just rebased this branch)
2. Install locally, run `thelma bee create`
3. Profit

cc @choover-broad as well

**Comment by mflinn-broad** [comment]
@rtitle and @aherbst-broad, I didn't realize this PR existed until it was mentioned in champions the other day. Most of us on DevOps have github notifications turned off because we have owner on so many repos, sorry we missed this but in the future it helps to drop a post in one of our slack channels to PRs like this :)

Were either of you successful in testing this, if not I can give it a whirl

**Comment by mflinn-broad** [comment]
Oh I see you did make a [post](https://broadinstitute.slack.com/archives/C029LTN5L80/p1669843395841909) apologies this must have gotten lost in the churn over the holidays.

**Comment by mflinn-broad** [comment]
I just tried creating a bee off this branch and got the following error from Sam
```
09:09 ERR 404 Not Found from https://sam.mflinn-rtitle-pr-test.bee.envs-terra.bio/api/resource/cloud-extension/azure/policies/fc-service-accounts ({"causes":[],"message":"Resource cloud-extension/azure not \
          found","source":"sam","stackTrace":[],"statusCode":404})
```

I assume this means that this call needs to happen first
```
curl -X 'POST' \
"https://sam/.${BEE_NAME}.bee.envs-terra.bio/api/resources/v2/cloud-extension/azure" \
  -H 'accept: */*' \
  -H "Authorization: Bearer $(gcloud auth print-access-token)" \
  -H 'Content-Type: application/json' \
  -d '{}'
```

**Comment by mflinn-broad** [comment]
https://terra.mflinn-rtitle-pr-test-2.bee.envs-terra.bio/ created successfully from this branch and sam cloud extension resource setup worked
Screenshot 2023-07-20 at 9 49 30 AM

**Comment by mflinn-broad** [comment]
> Q: how do I test this?

This is good feedback, thanks @rtitle. I've updated the README accordingly

**Review by choover-broad — APPROVED** [review]

**Pull request merged**
